async (page) => {
  const results=[];
  const check=async(condition,label)=>{if(!await condition)throw new Error(label);results.push(label);};
  await page.setViewportSize({width:1440,height:1000});
  await page.getByRole('button',{name:/Library/}).click();
  await check(page.locator('.word-row').count().then(n=>n===20),'Library: lists every word without pagination');
  await page.getByRole('textbox',{name:'Search library'}).fill('SERENDIPITY');
  await check(page.locator('.word-row').count().then(n=>n===1),'Search filters and ignores case');
  await page.getByRole('button',{name:'serendipity 意外發現美好事物的運氣',exact:false}).click();
  await check(page.getByRole('heading',{name:'serendipity',exact:true}).isVisible(),'Open detail');
  await page.getByRole('button',{name:'Next word',exact:true}).click();
  await check(page.getByRole('heading',{name:'serendipity',exact:true}).isVisible(),'Detail wraps within filtered results');
  await page.getByRole('button',{name:'Unstar word',exact:true}).click();
  await check(page.getByRole('button',{name:'Star word',exact:true}).isVisible(),'Detail star toggle');
  await page.getByRole('button',{name:'Back to library',exact:true}).click();
  await page.getByRole('button',{name:'Add word',exact:true}).click();
  await page.getByRole('button',{name:'Save word',exact:false}).click();
  await check(page.locator('#form-error').textContent().then(t=>t.includes('required')),'Required-field validation');
  await page.getByRole('textbox',{name:'Word',exact:false}).first().fill('qa-example');
  await page.getByRole('textbox',{name:'Meaning',exact:false}).fill('測試單字');
  await page.getByRole('textbox',{name:'Example 1',exact:true}).fill('This qa-example has meaning.');
  for(let i=0;i<4;i++)await page.getByRole('button',{name:'Add another example'}).click();
  await check(page.getByRole('button',{name:'Add another example'}).count().then(n=>n===0),'Five example maximum');
  for(let i=5;i>=2;i--)await page.getByRole('button',{name:`Remove example ${i}`,exact:true}).click();
  await check(page.getByRole('button',{name:'Remove example 1',exact:true}).count().then(n=>n===0),'One example minimum');
  await page.getByRole('button',{name:'Save word',exact:false}).click();
  await page.getByRole('heading',{name:'Today',exact:true}).waitFor();
  await page.getByRole('button',{name:/Library/}).click();
  await page.getByRole('textbox',{name:'Search library'}).fill('qa-example');
  await check(page.locator('.word-row').count().then(n=>n===1),'Created word searchable');
  await page.getByRole('button',{name:'Edit qa-example',exact:true}).click();
  await page.getByRole('textbox',{name:'Meaning',exact:false}).fill('更新後的中文');
  await page.getByRole('button',{name:'Update word',exact:false}).click();
  await page.getByRole('heading',{name:'Today',exact:true}).waitFor();
  await page.getByRole('button',{name:/Library/}).click();
  await check(page.locator('.word-meaning').textContent().then(t=>t==='更新後的中文'),'Edit persisted');
  await page.getByRole('button',{name:'Delete qa-example',exact:true}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await check(page.locator('.word-row').count().then(n=>n===1),'Delete cancel preserves word');
  await page.getByRole('button',{name:'Delete qa-example',exact:true}).click();
  await page.getByRole('button',{name:'Delete word',exact:true}).click();
  await page.getByRole('heading',{name:'No words found'}).waitFor();
  await check(page.locator('.word-row').count().then(n=>n===0),'Delete confirmation removes word');
  await page.getByRole('button',{name:'Clear filters',exact:true}).click();
  await page.screenshot({path:'output/playwright/library-desktop.png',fullPage:true});
  console.log(JSON.stringify(results));
}
