async (page) => {
  const results=[];const check=async(c,label)=>{if(!await c)throw Error(label);results.push(label);};
  await page.getByRole('button',{name:'Today',exact:true}).click();
  await page.locator('.customize>summary').click();
  await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('QA');
  await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('NEW');
  await check(page.getByRole('checkbox',{name:'Due only',exact:true}).isDisabled(),'New status disables Due only');
  await page.getByRole('combobox',{name:'Practice mode',exact:true}).selectOption('flip_zh');
  await page.getByRole('button',{name:'Start today’s review',exact:true}).last().click();
  await check(page.getByRole('heading',{name:'匯入測試',exact:true}).isVisible(),'Flip ZH starts with Chinese');
  await page.getByRole('button',{name:'Settings',exact:true}).click();
  await check(page.getByRole('dialog').isVisible(),'Settings requires leaving active review');
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.getByRole('button',{name:'Reveal answer',exact:true}).click();
  await check(page.getByRole('heading',{name:'qa-import',exact:true}).isVisible(),'Flip reveals target word');
  await page.getByRole('button',{name:'Exit session',exact:false}).click();
  await page.getByRole('button',{name:'Cancel',exact:true}).click();
  await check(page.locator('.review-card').isVisible(),'Exit cancellation keeps session');
  await page.getByRole('button',{name:'I knew it',exact:false}).click();
  await check(page.locator('.result-score').textContent().then(t=>/1\s*\/\s*1/.test(t)),'Flip completion score');
  await check(page.locator('.sync-status').textContent().then(t=>t.includes('saved')),'Completion saves stats');
  await page.getByRole('button',{name:'Back to today',exact:false}).click();
  await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('ALL');
  await page.getByRole('checkbox',{name:'Due only',exact:true}).uncheck();
  await page.getByRole('combobox',{name:'Practice mode',exact:true}).selectOption('spelling');
  await page.getByRole('button',{name:'Start today’s review',exact:true}).last().click();
  await page.getByRole('textbox',{name:'Your answer',exact:true}).fill('wrong');
  await page.getByRole('textbox',{name:'Your answer',exact:true}).press('Enter');
  await check(page.locator('#answer-feedback').textContent().then(t=>t.includes('Not quite')),'Wrong spelling keeps input available');
  await page.getByRole('textbox',{name:'Your answer',exact:true}).fill('  QA-IMPORT  ');
  await page.getByRole('textbox',{name:'Your answer',exact:true}).press('Enter');
  await page.locator('.result-score').waitFor();
  await check(page.locator('.result-score').textContent().then(t=>/0\s*\/\s*1/.test(t)),'Retry success remains a recall failure');
  await check(page.locator('.revisit').textContent().then(t=>t.includes('qa-import')),'Missed word shown in recap');
  await page.getByRole('button',{name:'Back to today',exact:false}).click();
  await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('Little moments');
  await page.getByRole('combobox',{name:'Practice mode',exact:true}).selectOption('fill_blank');
  await page.getByRole('button',{name:'Start today’s review',exact:true}).last().click();
  await check(page.locator('.blank').isVisible(),'Cloze renders a blank');
  await page.getByRole('button',{name:'I don’t know',exact:false}).click();
  await check(page.locator('#answer-feedback').textContent().then(t=>t.includes('The answer is')),'Cloze reveal answer');
  const before=await page.locator('.review-progress').textContent();
  await page.keyboard.press('Enter');
  await check(page.locator('.review-progress').textContent().then(t=>t!==before),'Enter advances revealed card');
  await page.getByRole('button',{name:'Exit session',exact:false}).click();
  await page.getByRole('button',{name:'Leave session',exact:true}).click();
  await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('Personal growth');
  await check(page.locator('.settings-bottom').textContent().then(t=>t.includes('1 without a cloze example excluded')),'Unavailable cloze example excluded');
  await page.getByRole('combobox',{name:'Type',exact:true}).selectOption('phrase');
  await check(page.getByRole('combobox',{name:'Practice mode',exact:true}).inputValue().then(v=>v==='flip_en'),'Phrases reset Cloze mode');
  await check(page.locator('option[value="fill_blank"]').evaluate(el=>el.disabled),'Phrases disable Cloze');
  await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('LEARNING');
  await page.getByRole('button',{name:'Start today’s review',exact:true}).last().click();
  await check(page.locator('#toast').textContent().then(t=>t.includes('No cards match')),'No matching cards gives feedback');
  await page.getByRole('combobox',{name:'Type',exact:true}).selectOption('word');
  await page.getByRole('combobox',{name:'Category',exact:true}).selectOption('ALL');
  await page.getByRole('combobox',{name:'Status',exact:true}).selectOption('ALL');
  await page.getByRole('button',{name:'Start today’s review',exact:true}).last().click();
  await page.getByRole('button',{name:'Reveal answer',exact:true}).click();
  await page.getByRole('button',{name:'I forgot',exact:false}).click();
  await page.getByRole('button',{name:'Exit session',exact:false}).click();
  await page.getByRole('button',{name:'Leave session',exact:true}).click();
  await page.getByRole('heading',{name:'Today',exact:true}).waitFor();
  await check(page.getByRole('heading',{name:'Today',exact:true}).isVisible(),'Partially answered session exits to Today');
  console.log(JSON.stringify(results));
}
